# --- Database ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://app-db:5432/frequent_flier
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.hibernate-orm.database.generation=update
spring.jpa.show-sql=true
# --- JWT ---
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
quarkus.smallrye-jwt.sign.key-location=META-INF/resources/privateKey.pem
mp.jwt.verify.issuer=frequent-flier-app
quarkus.smallrye-jwt.token.expiration=3600