# persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frequent-flier-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/frequent-flier-db"